version: '3.5'

services:
  database:
    hostname: database
    build:
      context: .
      dockerfile: build/postgres/Dockerfile  
      args:
        LCA_VERSION: "8510029b1_ENU"
    image: genesys-postgres
    restart: always
    env_file:
      - ./config/database.env
    volumes:
      - "./data/postgresql:/var/lib/postgresql/data"

  flexlm:
    hostname: flexlm
    #mac_address: 00:00:00:00:00:00
    build:
      context: .
      dockerfile: build/flexlm/Dockerfile
      args:
        LCA_VERSION: "8510029b1_ENU"
    image: genesys-flexlm
    restart: always
    volumes:
      - "./config/license.dat:/run/secrets/license.dat:ro"